import { useState, useEffect, useRef, useCallback } from 'react'
import {
  RiImage2Line,
  RiFolderOpenLine,
  RiCloseLine,
  RiMagicLine,
  RiFileWarningLine,
  RiArrowLeftSLine,
  RiArrowRightSLine,
  RiDownloadLine
} from 'react-icons/ri'
import { motion, AnimatePresence } from 'framer-motion'

interface GalleryImage {
  filename: string
  displayName: string
  path: string
  url: string
  createdAt: Date
}

const GalleryView = () => {
  const [allImages, setAllImages] = useState<GalleryImage[]>([])
  const [visibleImages, setVisibleImages] = useState<GalleryImage[]>([])
  const [selectedImage, setSelectedImage] = useState<GalleryImage | null>(null)
  const [direction, setDirection] = useState(0)
  const [page, setPage] = useState(1)
  const ITEMS_PER_PAGE = 12
  const observer = useRef<IntersectionObserver | null>(null)

  const lastImageRef = useCallback(
    (node: HTMLDivElement) => {
      if (observer.current) observer.current.disconnect()
      observer.current = new IntersectionObserver((entries) => {
        if (entries[0].isIntersecting && visibleImages.length < allImages.length) {
          setPage((prev) => prev + 1)
        }
      })
      if (node) observer.current.observe(node)
    },
    [visibleImages.length, allImages.length]
  )

  const fetchGallery = async () => {
    try {
      const data = await window.electron.ipcRenderer.invoke('get-gallery')
      if (Array.isArray(data)) setAllImages(data)
    } catch (e) {}
  }

  useEffect(() => {
    fetchGallery()
    const interval = setInterval(fetchGallery, 5000)
    return () => clearInterval(interval)
  }, [])

  useEffect(() => {
    const endIndex = page * ITEMS_PER_PAGE
    setVisibleImages(allImages.slice(0, endIndex))
  }, [page, allImages])

  const openLocation = async (path: string, e?: React.MouseEvent) => {
    e?.stopPropagation()
    await window.electron.ipcRenderer.invoke('open-image-location', path)
  }

  const saveCopy = async (path: string, e?: React.MouseEvent) => {
    e?.stopPropagation()
    await window.electron.ipcRenderer.invoke('save-image-external', path)
  }

  const navigateImage = useCallback(
    (newDirection: number) => {
      if (!selectedImage || allImages.length === 0) return
      setDirection(newDirection)
      const currentIndex = allImages.findIndex((img) => img.filename === selectedImage.filename)
      if (currentIndex === -1) return
      let newIndex = currentIndex + newDirection
      if (newIndex >= allImages.length) newIndex = 0
      if (newIndex < 0) newIndex = allImages.length - 1
      setSelectedImage(allImages[newIndex])
    },
    [selectedImage, allImages]
  )

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (!selectedImage) return
      if (e.key === 'ArrowRight') navigateImage(1)
      if (e.key === 'ArrowLeft') navigateImage(-1)
      if (e.key === 'Escape') setSelectedImage(null)
    }
    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [selectedImage, navigateImage])

  const variants = {
    enter: (dir: number) => ({ x: dir > 0 ? 800 : -800, opacity: 0, scale: 0.9 }),
    center: { zIndex: 1, x: 0, opacity: 1, scale: 1 },
    exit: (dir: number) => ({ zIndex: 0, x: dir < 0 ? 800 : -800, opacity: 0, scale: 0.9 })
  }

  return (
    <div className="flex-1 bg-[#040407] h-full p-6 flex flex-col overflow-hidden animate-in fade-in duration-300">
      
      {/* Header */}
      <div className="flex items-center justify-between pb-5 border-b border-white/[0.05] mb-5 shrink-0">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-violet-600/10 border border-violet-500/20 flex items-center justify-center">
            <RiImage2Line className="text-violet-400" size={18} />
          </div>
          <div>
            <h2 className="text-[13px] font-semibold text-zinc-200 tracking-tight">Visual Vault</h2>
            <p className="text-[10px] text-zinc-600 font-mono mt-0.5">GENERATED BY ELI</p>
          </div>
        </div>
        <div className="flex items-center gap-1.5 text-[10px] font-mono text-violet-300 bg-violet-500/8 px-3 py-1.5 rounded-full border border-violet-500/15">
          <RiMagicLine size={11} /> {allImages.length} artifacts
        </div>
      </div>

      {/* Grid */}
      <div className="flex-1 overflow-y-auto scrollbar-small pr-1 min-h-0">
        {allImages.length === 0 ? (
          <div className="h-full flex flex-col items-center justify-center text-zinc-700 gap-4">
            <div className="w-16 h-16 rounded-2xl bg-white/[0.02] flex items-center justify-center border border-white/[0.04]">
              <RiImage2Line size={28} className="opacity-25" />
            </div>
            <p className="text-[11px] text-zinc-600 font-mono tracking-widest">NO ARTIFACTS FOUND</p>
          </div>
        ) : (
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4 pb-8">
            {visibleImages.map((img, index) => {
              const isLast = index === visibleImages.length - 1
              return (
                <div
                  key={`${img.filename}-${index}`}
                  ref={isLast ? lastImageRef : null}
                  onClick={() => {
                    setDirection(0)
                    setSelectedImage(img)
                  }}
                  className="group relative aspect-video bg-[#0d0d14] rounded-xl border border-white/[0.05] overflow-hidden hover:border-violet-500/30 hover:shadow-[0_0_24px_rgba(124,58,237,0.12)] transition-all duration-300 cursor-pointer"
                >
                  <img
                    src={img.url}
                    alt={img.displayName}
                    loading="lazy"
                    onError={(e) => {
                      e.currentTarget.style.display = 'none'
                      e.currentTarget.nextElementSibling?.classList.remove('hidden')
                    }}
                    className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105 opacity-75 group-hover:opacity-100"
                  />
                  {/* Error fallback */}
                  <div className="hidden absolute inset-0 items-center justify-center flex-col gap-2 bg-[#0d0d14]">
                    <RiFileWarningLine className="text-red-500/40" size={20} />
                    <span className="text-[8px] text-zinc-600">RENDER ERROR</span>
                  </div>
                  {/* Hover overlay */}
                  <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-all duration-300 flex flex-col justify-end p-3">
                    <p className="text-[10px] text-zinc-200 line-clamp-1 font-semibold mb-0.5 capitalize">
                      {img.displayName}
                    </p>
                    <p className="text-[8px] text-violet-400 font-mono mb-2.5 tracking-wide">
                      {new Date(img.createdAt).toLocaleDateString()}
                    </p>
                    <div className="flex gap-1.5 justify-end">
                      <button
                        onClick={(e) => openLocation(img.path, e)}
                        className="p-1.5 bg-white/10 backdrop-blur-sm text-zinc-300 rounded-lg hover:bg-white/20 transition-all border border-white/10"
                        title="Open File Location"
                      >
                        <RiFolderOpenLine size={12} />
                      </button>
                    </div>
                  </div>
                </div>
              )
            })}
          </div>
        )}
      </div>

      {/* Lightbox */}
      <AnimatePresence>
        {selectedImage && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.25 }}
            className="fixed inset-0 z-[9999] bg-black/95 backdrop-blur-sm flex items-center justify-center"
          >
            {/* Close */}
            <button
              onClick={() => setSelectedImage(null)}
              className="cursor-pointer absolute top-5 right-5 p-2.5 bg-white/[0.05] hover:bg-red-500/20 hover:text-red-400 rounded-xl text-zinc-400 transition-all border border-white/[0.06] z-50"
            >
              <RiCloseLine size={20} />
            </button>

            {/* Left Nav */}
            <div
              className="absolute left-0 top-0 bottom-0 w-24 z-40 flex items-center justify-start pl-4 group cursor-pointer"
              onClick={() => navigateImage(-1)}
            >
              <div className="p-3 bg-white/[0.04] group-hover:bg-violet-500/20 text-zinc-500 group-hover:text-violet-300 rounded-xl transition-all border border-white/[0.05] group-hover:border-violet-500/30 transform group-hover:-translate-x-0.5">
                <RiArrowLeftSLine size={24} />
              </div>
            </div>

            {/* Right Nav */}
            <div
              className="absolute right-0 top-0 bottom-0 w-24 z-40 flex items-center justify-end pr-4 group cursor-pointer"
              onClick={() => navigateImage(1)}
            >
              <div className="p-3 bg-white/[0.04] group-hover:bg-violet-500/20 text-zinc-500 group-hover:text-violet-300 rounded-xl transition-all border border-white/[0.05] group-hover:border-violet-500/30 transform group-hover:translate-x-0.5">
                <RiArrowRightSLine size={24} />
              </div>
            </div>

            {/* Image Viewer */}
            <div className="relative w-full h-full flex flex-col items-center justify-center overflow-hidden">
              <div className="relative w-full max-w-6xl h-[72vh] flex items-center justify-center">
                <AnimatePresence initial={false} custom={direction} mode="popLayout">
                  <motion.img
                    key={selectedImage.filename}
                    src={selectedImage.url}
                    custom={direction}
                    variants={variants}
                    initial="enter"
                    animate="center"
                    exit="exit"
                    transition={{ x: { type: 'spring', stiffness: 280, damping: 28 }, opacity: { duration: 0.15 } }}
                    className="absolute max-w-full max-h-full rounded-2xl shadow-[0_32px_80px_rgba(0,0,0,0.8)] border border-white/[0.08] object-contain"
                  />
                </AnimatePresence>
              </div>

              {/* Image Info */}
              <div className="absolute bottom-8 z-50 flex flex-col items-center gap-4">
                <div className="px-5 py-3 bg-black/70 backdrop-blur-xl rounded-2xl border border-white/[0.07] text-center">
                  <h3 className="text-[14px] font-semibold text-white mb-0.5 capitalize">{selectedImage.displayName}</h3>
                  <p className="text-[10px] text-zinc-500 font-mono">
                    {new Date(selectedImage.createdAt).toLocaleString()} · ELI Generated
                  </p>
                </div>
                <div className="flex gap-3">
                  <motion.button
                    whileHover={{ scale: 1.03 }}
                    whileTap={{ scale: 0.97 }}
                    onClick={() => openLocation(selectedImage.path)}
                    className="cursor-pointer flex items-center gap-2 px-5 py-2 bg-white/[0.06] hover:bg-white/[0.10] text-zinc-300 rounded-xl text-[11px] font-semibold tracking-wide transition-all border border-white/[0.07] hover:border-white/[0.14]"
                  >
                    <RiFolderOpenLine size={14} /> Open Folder
                  </motion.button>
                  <motion.button
                    whileHover={{ scale: 1.03 }}
                    whileTap={{ scale: 0.97 }}
                    onClick={() => saveCopy(selectedImage.path)}
                    className="cursor-pointer flex items-center gap-2 px-5 py-2 bg-violet-600/15 hover:bg-violet-600/25 text-violet-300 rounded-xl text-[11px] font-semibold tracking-wide transition-all border border-violet-500/20 hover:border-violet-500/35"
                  >
                    <RiDownloadLine size={14} /> Save Copy
                  </motion.button>
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}

export default GalleryView
